dist: trusty
language: python
install:
  - sudo apt-get update
  - sudo apt-get -y install libav-tools
  - pip install coveralls tox
  - cd coconuts/static
  - npm install
  - cd ../..
script:
  - tox
  - cd coconuts/static
  - npm test
after_success: coveralls
