addons:
  apt:
    packages:
    - ffmpeg
after_success: bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - coconuts/static/node_modules
  pip: true
dist: xenial
install:
  - pip install coverage tox
  - cd coconuts/static
  - npm install
  - cd ../..
language: python
script:
  - tox
  - cd coconuts/static
  - npm test -- --single-run
  - cd ../..
