addons:
  apt:
    packages:
    - ffmpeg
after_success: bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - coconuts/static/node_modules
  pip: true
dist: xenial
install:
  - pip install -r requirements.txt coverage
  - cd coconuts/static
  - npm install
  - cd ../..
language: python
python: 3.5
script:
  - coverage run --branch ./manage.py test
  - cd coconuts/static
  - npm test -- --single-run
  - cd ../..
